### ISSUE TITLE
총기 저주받았을 때의 스펙 정리

### ISSUE THREAD

**Issue by nelpsos** [Hoto-Mocha/Stopped-Project#10]
- [x] 발사
- [ ] 장전
- [ ] 근접공격
- [ ] 밀치기
- [ ] 탈착불가
- [ ] 장탄수 표시 
- [ ] 그 외 기타등등 

스펙을 정리하여 문서화

**Comment by Hoto-Mocha** [comment]
총기가 저주받았을 경우

    - 해제 불가능

    - 발사 시 

      - 30% 정상 발사

      - 20% 탄환은 소모되지만 발사 X
      - 20% 총알이 전방 3칸까지만 이동

      - 10% 맞은 적은 2칸, 플레이어는 뒤로 한 칸 물러남
      - 10% 플레이어 위치에 폭탄 폭발

      - 2% 탄환 피해가 없고 맞은 대상을 (층수 + 2)만큼 치유, 최대 체력을 넘을 시 초과량만큼 보호막 제공
      - 2% 맞은 적에게 10턴간 아드레날린 효과 부여
      - 2% 맞은 적에게 5턴간 불구 부여(다리 맞췄다는 설정)
      - 2% 강제 재장전

      - 1% 음침효과(머리 맞췄다는 설정)
      - 1% 장전된 탄환이 가방으로 되돌아감

녹픽던 모딩 기획서.md에 추가했습니다
