### ISSUE TITLE
추가 필요 텍스트

### ISSUE THREAD

**Issue by nelpsos** [Hoto-Mocha/Stopped-Project#15]
1. 인챈트는 결국 불가능?(그렇다면 이것에 대한 설명 메시지도 포함)
2. 감정 텍스트
3. 재장전 실패 텍스트(전부 다 차 있을 때 실패)

**Comment by Hoto-Mocha** [comment]
1. 총기는 그 복잡한 구조에 의해 마법부여의 영향을 받지 않을 것입니다.

2-1. 주문서가 (총기이름)을/를 감정했다.
2-2.당신은 이 총기에 대해 충분히 알 만큼 익숙해졌습니다.(정확히는 기억이 나질 않는데 무기 자연감정할때 나오는 것과 동일)

3. 이미 모든 탄환이 장전되어 있다.

**Comment by Hoto-Mocha** [comment]
https://github.com/00-Evan/shattered-pixel-dungeon/blob/4aed22a4f2ebea34e42fa961ee17f97588ca1acf/core/src/main/assets/messages/items/items_ko.properties#L895

2-1은 이걸로 사용하면 될 것 같습니다.
