### ISSUE TITLE
해야 할 것

### ISSUE THREAD

**Issue by Hoto-Mocha** [Hoto-Mocha/Stopped-Project#7]
- [ ] 점착 유탄 효과 추가
- [ ] 점착 유탄 특성 추가
- [ ] 점착 유탄 특성 추가에 따른 특성 아이콘 추가
- [ ] 탄환 스프라이트 추가
- [ ] 캐릭터 스프라이트 구상

**Comment by nelpsos** [comment]
얘네를 다 따로 쪼개서 이슈로 등록해 주세요.
그리고 레이블도 문서 작업으로 등록하면 좋을 것 같아요.
문서로 하나로 퉁치는게 좀 구별이 부족하다 싶으시면 레이블을 추가해주시면 되겠습니다(추가는 오른쪽 Labels 옆의 톱니바퀴 누르면 할 수 있음)

**Comment by Hoto-Mocha** [comment]
ㅇㅋㅇㅋ
